language: node_js
node_js:
  - "6"
dist: trusty

cache:
  directories:
    - "node_modules"

script:
  - webpack  # Build the SPA
  - cp -Rf include_in_dist/. dist/ # Copy the static folder to the distribution folder.

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard.
  on:
    branch: master
  local_dir: dist

